### ISSUE TITLE
Hey, Filip. why do you have 'Jew' in 'unsafe.dart' file?

### ISSUE THREAD

**Issue by beingRD** [filiph/english_words#11]
What is this — a 1950s country club in Minnesota where words like J-E-W can only be whispered? I get it it's not polite but still, it's rather strange. I prefer saying 'Jewish'. But if you are including an unsafe word based on religion or race you should include the n- word as well.
It just doesn't make sense!
```
const List<String> unsafe = [
  'AIDS',
  'ass',
  'fucking',
  'gay',
  'Jew',
  'rape',
  'sex',
  'shit'
];
```

**Comment by filiph** [comment]
Hi, sorry for the late reply.

This list was constructed kind of willy nilly, with no real strategy, just by using the `WordPair` functionality and seeing what seems wrong. While Jew in itself is completely fine, when paired with some other words in the corpus, the resulting word-pair it can feel downright hateful. So that's why I included it here. There are probably other normal words in the corpus that have this same effect, but I haven't seen them yet.

>  you should include the n- word as well

The `unsafe` list just includes words that are in the corpus. The n- word isn't there, so it doesn't need to be here. If it was there, I would definitely add it.

**Comment by filiph** [comment]
I'll close this, but feel free to reopen if you feel strongly about this.
